//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HellManagerWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConnectionStringHellDB : DbContext
    {
        public ConnectionStringHellDB()
            : base("name=ConnectionStringHellDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<PunisherRank> PunisherRanks { get; set; }
        public virtual DbSet<Punisher> Punishers { get; set; }
        public virtual DbSet<Punishment> Punishments { get; set; }
        public virtual DbSet<SinDegree> SinDegrees { get; set; }
        public virtual DbSet<Sinner> Sinners { get; set; }
        public virtual DbSet<Sin> Sins { get; set; }
    
        public virtual int usp_GendersDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GendersDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_GendersInsert_Result> usp_GendersInsert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GendersInsert_Result>("usp_GendersInsert", nameParameter);
        }
    
        public virtual ObjectResult<usp_GendersSelect_Result> usp_GendersSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GendersSelect_Result>("usp_GendersSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_GendersUpdate_Result> usp_GendersUpdate(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GendersUpdate_Result>("usp_GendersUpdate", idParameter, nameParameter);
        }
    
        public virtual int usp_PunisherRanksDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PunisherRanksDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_PunisherRanksInsert_Result> usp_PunisherRanksInsert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunisherRanksInsert_Result>("usp_PunisherRanksInsert", nameParameter);
        }
    
        public virtual ObjectResult<usp_PunisherRanksSelect_Result> usp_PunisherRanksSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunisherRanksSelect_Result>("usp_PunisherRanksSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_PunisherRanksUpdate_Result> usp_PunisherRanksUpdate(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunisherRanksUpdate_Result>("usp_PunisherRanksUpdate", idParameter, nameParameter);
        }
    
        public virtual int usp_PunishersDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PunishersDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_PunishersInsert_Result> usp_PunishersInsert(string name, string phone, Nullable<int> punisherRankId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var punisherRankIdParameter = punisherRankId.HasValue ?
                new ObjectParameter("PunisherRankId", punisherRankId) :
                new ObjectParameter("PunisherRankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishersInsert_Result>("usp_PunishersInsert", nameParameter, phoneParameter, punisherRankIdParameter);
        }
    
        public virtual ObjectResult<usp_PunishersSelect_Result> usp_PunishersSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishersSelect_Result>("usp_PunishersSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_PunishersUpdate_Result> usp_PunishersUpdate(Nullable<int> id, string name, string phone, Nullable<int> punisherRankId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var punisherRankIdParameter = punisherRankId.HasValue ?
                new ObjectParameter("PunisherRankId", punisherRankId) :
                new ObjectParameter("PunisherRankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishersUpdate_Result>("usp_PunishersUpdate", idParameter, nameParameter, phoneParameter, punisherRankIdParameter);
        }
    
        public virtual int usp_PunishmentsDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PunishmentsDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_PunishmentsInsert_Result> usp_PunishmentsInsert(string name, Nullable<int> treatCycle)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var treatCycleParameter = treatCycle.HasValue ?
                new ObjectParameter("TreatCycle", treatCycle) :
                new ObjectParameter("TreatCycle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishmentsInsert_Result>("usp_PunishmentsInsert", nameParameter, treatCycleParameter);
        }
    
        public virtual ObjectResult<usp_PunishmentsSelect_Result> usp_PunishmentsSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishmentsSelect_Result>("usp_PunishmentsSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_PunishmentsUpdate_Result> usp_PunishmentsUpdate(Nullable<int> id, string name, Nullable<int> treatCycle)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var treatCycleParameter = treatCycle.HasValue ?
                new ObjectParameter("TreatCycle", treatCycle) :
                new ObjectParameter("TreatCycle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PunishmentsUpdate_Result>("usp_PunishmentsUpdate", idParameter, nameParameter, treatCycleParameter);
        }
    
        public virtual int usp_SinDegreesDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SinDegreesDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_SinDegreesInsert_Result> usp_SinDegreesInsert(string name, Nullable<int> value)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinDegreesInsert_Result>("usp_SinDegreesInsert", nameParameter, valueParameter);
        }
    
        public virtual ObjectResult<usp_SinDegreesSelect_Result> usp_SinDegreesSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinDegreesSelect_Result>("usp_SinDegreesSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_SinDegreesUpdate_Result> usp_SinDegreesUpdate(Nullable<int> id, string name, Nullable<int> value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var valueParameter = value.HasValue ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinDegreesUpdate_Result>("usp_SinDegreesUpdate", idParameter, nameParameter, valueParameter);
        }
    
        public virtual int usp_SinnersDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SinnersDelete", idParameter);
        }
    
        public virtual int usp_SinnerSinDelete(Nullable<int> sinners_Id, Nullable<int> sins_Id)
        {
            var sinners_IdParameter = sinners_Id.HasValue ?
                new ObjectParameter("Sinners_Id", sinners_Id) :
                new ObjectParameter("Sinners_Id", typeof(int));
    
            var sins_IdParameter = sins_Id.HasValue ?
                new ObjectParameter("Sins_Id", sins_Id) :
                new ObjectParameter("Sins_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SinnerSinDelete", sinners_IdParameter, sins_IdParameter);
        }
    
        public virtual ObjectResult<usp_SinnerSinInsert_Result> usp_SinnerSinInsert(Nullable<int> sinners_Id, Nullable<int> sins_Id)
        {
            var sinners_IdParameter = sinners_Id.HasValue ?
                new ObjectParameter("Sinners_Id", sinners_Id) :
                new ObjectParameter("Sinners_Id", typeof(int));
    
            var sins_IdParameter = sins_Id.HasValue ?
                new ObjectParameter("Sins_Id", sins_Id) :
                new ObjectParameter("Sins_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnerSinInsert_Result>("usp_SinnerSinInsert", sinners_IdParameter, sins_IdParameter);
        }
    
        public virtual ObjectResult<usp_SinnerSinSelect_Result> usp_SinnerSinSelect(Nullable<int> sinners_Id, Nullable<int> sins_Id)
        {
            var sinners_IdParameter = sinners_Id.HasValue ?
                new ObjectParameter("Sinners_Id", sinners_Id) :
                new ObjectParameter("Sinners_Id", typeof(int));
    
            var sins_IdParameter = sins_Id.HasValue ?
                new ObjectParameter("Sins_Id", sins_Id) :
                new ObjectParameter("Sins_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnerSinSelect_Result>("usp_SinnerSinSelect", sinners_IdParameter, sins_IdParameter);
        }
    
        public virtual ObjectResult<usp_SinnersInsert_Result> usp_SinnersInsert(string fullName, Nullable<int> age, string jobTitle, Nullable<int> salary, Nullable<int> genderId)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("JobTitle", jobTitle) :
                new ObjectParameter("JobTitle", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(int));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnersInsert_Result>("usp_SinnersInsert", fullNameParameter, ageParameter, jobTitleParameter, salaryParameter, genderIdParameter);
        }
    
        public virtual ObjectResult<usp_SinnerSinUpdate_Result> usp_SinnerSinUpdate(Nullable<int> sinners_Id, Nullable<int> sins_Id)
        {
            var sinners_IdParameter = sinners_Id.HasValue ?
                new ObjectParameter("Sinners_Id", sinners_Id) :
                new ObjectParameter("Sinners_Id", typeof(int));
    
            var sins_IdParameter = sins_Id.HasValue ?
                new ObjectParameter("Sins_Id", sins_Id) :
                new ObjectParameter("Sins_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnerSinUpdate_Result>("usp_SinnerSinUpdate", sinners_IdParameter, sins_IdParameter);
        }
    
        public virtual ObjectResult<usp_SinnersSelect_Result> usp_SinnersSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnersSelect_Result>("usp_SinnersSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_SinnersUpdate_Result> usp_SinnersUpdate(Nullable<int> id, string fullName, Nullable<int> age, string jobTitle, Nullable<int> salary, Nullable<int> genderId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("JobTitle", jobTitle) :
                new ObjectParameter("JobTitle", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(int));
    
            var genderIdParameter = genderId.HasValue ?
                new ObjectParameter("GenderId", genderId) :
                new ObjectParameter("GenderId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinnersUpdate_Result>("usp_SinnersUpdate", idParameter, fullNameParameter, ageParameter, jobTitleParameter, salaryParameter, genderIdParameter);
        }
    
        public virtual int usp_SinsDelete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SinsDelete", idParameter);
        }
    
        public virtual ObjectResult<usp_SinsInsert_Result> usp_SinsInsert(string name, Nullable<int> punishmentId, Nullable<int> punisherId, Nullable<int> sinDegreeId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var punishmentIdParameter = punishmentId.HasValue ?
                new ObjectParameter("PunishmentId", punishmentId) :
                new ObjectParameter("PunishmentId", typeof(int));
    
            var punisherIdParameter = punisherId.HasValue ?
                new ObjectParameter("PunisherId", punisherId) :
                new ObjectParameter("PunisherId", typeof(int));
    
            var sinDegreeIdParameter = sinDegreeId.HasValue ?
                new ObjectParameter("SinDegreeId", sinDegreeId) :
                new ObjectParameter("SinDegreeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinsInsert_Result>("usp_SinsInsert", nameParameter, punishmentIdParameter, punisherIdParameter, sinDegreeIdParameter);
        }
    
        public virtual ObjectResult<usp_SinsSelect_Result> usp_SinsSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinsSelect_Result>("usp_SinsSelect", idParameter);
        }
    
        public virtual ObjectResult<usp_SinsUpdate_Result> usp_SinsUpdate(Nullable<int> id, string name, Nullable<int> punishmentId, Nullable<int> punisherId, Nullable<int> sinDegreeId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var punishmentIdParameter = punishmentId.HasValue ?
                new ObjectParameter("PunishmentId", punishmentId) :
                new ObjectParameter("PunishmentId", typeof(int));
    
            var punisherIdParameter = punisherId.HasValue ?
                new ObjectParameter("PunisherId", punisherId) :
                new ObjectParameter("PunisherId", typeof(int));
    
            var sinDegreeIdParameter = sinDegreeId.HasValue ?
                new ObjectParameter("SinDegreeId", sinDegreeId) :
                new ObjectParameter("SinDegreeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SinsUpdate_Result>("usp_SinsUpdate", idParameter, nameParameter, punishmentIdParameter, punisherIdParameter, sinDegreeIdParameter);
        }
    }
}
