//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HellManagerWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunisherRank
    {
        public PunisherRank()
        {
            this.Punishers = new HashSet<Punisher>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Punisher> Punishers { get; set; }
    }
}
