//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HellManagerWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinner
    {
        public Sinner()
        {
            this.Sins = new HashSet<Sin>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Sin> Sins { get; set; }
    }
}
